[versions]
jdk = "8"
groovy = "3.0.18"
codenarc = "3.3.0"

[plugins]
git-publish = "org.ajoberstar.git-publish:3.0.1" # max for jdk8
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
rulebook-codenarc = "com.hendraanggrian.rulebook:rulebook-codenarc:0.4"
# main
groovy = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
# test
truth = "com.google.truth:truth:1.1.5"
